[package]
name = "nonogram"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "solver_benches"
harness = false

[[bench]]
name = "generator_benches"
harness = false